// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUserConnections(ctx context.Context, user1 string) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (*CreateAttachmentRow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (string, error)
	CreateGroupAttachement(ctx context.Context, arg CreateGroupAttachementParams) (*CreateGroupAttachementRow, error)
	CreateGroupMessages(ctx context.Context, arg CreateGroupMessagesParams) (pgtype.Text, error)
	CreateGroupParticiPants(ctx context.Context, arg CreateGroupParticiPantsParams) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (pgtype.Text, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserConnectionWith(ctx context.Context, arg CreateUserConnectionWithParams) (*CreateUserConnectionWithRow, error)
	FindAttachmentByID(ctx context.Context, id string) (*Attachment, error)
	FindMessageByConnectionID(ctx context.Context, arg FindMessageByConnectionIDParams) ([]*Message, error)
	FindMessageByID(ctx context.Context, id pgtype.Text) (*Message, error)
	FindUserByID(ctx context.Context, id string) (*User, error)
	FindUserConnectionsByID(ctx context.Context, id string) (*UserConnection, error)
	FindUserConnectionsWith(ctx context.Context, arg FindUserConnectionsWithParams) (*UserConnection, error)
	LisAttachmentByMessageID(ctx context.Context, idMessages string) ([]*Attachment, error)
	ListAttachmentByUserCon(ctx context.Context, arg ListAttachmentByUserConParams) ([]*Attachment, error)
	ListGroupAttachments(ctx context.Context, arg ListGroupAttachmentsParams) ([]*GroupAttachment, error)
	ListGroupMessages(ctx context.Context, arg ListGroupMessagesParams) ([]*GroupMessage, error)
	ListGroupParticipants(ctx context.Context, groupID string) ([]string, error)
	ListGroupsByName(ctx context.Context, dollar_1 pgtype.Text) ([]*Group, error)
	ListMessageAttachments(ctx context.Context, idMessage string) ([]*GroupAttachment, error)
	ListUserConnectWith(ctx context.Context, dollar_1 pgtype.Text) ([]string, error)
	ListUserConnectionsID(ctx context.Context, user1 string) ([]string, error)
	ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]string, error)
	ListUserMessages(ctx context.Context, arg ListUserMessagesParams) ([]*Message, error)
	ListUserMessagesByConetent(ctx context.Context, dollar_1 pgtype.Text) ([]*Message, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
